# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_vote_date', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TweetVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_result', models.TextField(max_length=10)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_vote.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(editable=False, max_length=32)),
                ('first_authorize_date', models.DateTimeField(auto_now=True)),
                ('lang', models.TextField(max_length=10)),
                ('access_token', models.TextField(max_length=50)),
                ('remember_me_token', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
        ),
        migrations.AddField(
            model_name='tweetvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_vote.User'),
        ),
        migrations.AlterUniqueTogether(
            name='tweetvote',
            unique_together=set([('user', 'tweet')]),
        ),
    ]
