# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='oauth_token',
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_secret',
            field=models.TextField(default='aserot', max_length=50),
            preserve_default=False,
        ),
    ]
