# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_vote', '0002_auto_20170308_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_icon',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
